### ISSUE TITLE
Invalid linker flag in pkg-config file

### ISSUE THREAD

**Issue by stv0g** [mccdaq/uldaq#19] opened 2020-05-11 10:56 UTC
https://github.com/mccdaq/uldaq/blob/0b72c315361bae40e630ea93990bef4cc6b8597c/libuldaq.pc.in#L9

It should be `-luldaq` not `-libuldaq`

**Comment by sbazaz** [comment] 2020-05-11 21:22
The issue is fixed in Version 1.2.0

Thank you

**Closed as completed by sbazaz** 2020-05-11 21:22 UTC
